### ISSUE TITLE
Password encoder

### ISSUE THREAD

**Issue by clubdesarrolladores** [DavidBadura/FixturesBundle#12]
Hi David.

I am using FOSUserBundle and this is the fixture:

```
user:
    properties:
        class: WebFactory\Bundle\UserBundle\Entity\User
    data:
        seller:
            username: seller
            email: seller@localhost
            password: seller
            enabled: true
            roles: [ROLE_SELLER]
        admin:
            username: admin
            email: admin@localhost
            password: admin
            enabled: true
            roles: [ROLE_ADMIN]
        superadmin:
            username: superadmin
            email: superadmin@localhost
            password: superadmin
            enabled: true
            roles: [ROLE_SUPERADMIN]
```

All its ok, but the passwords are not encoded.

Thanks.
